spring:

  datasource:
    url: jdbc:h2:mem:base;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      database: H2
      show-sql: true
  thymeleaf:
    cache: false

  pidfile: shared/tmp/pids/application.pid
server:
  port: 10001

logging:
    level:
        org.springframework: 'OFF'
        com.xiaojiuwo.models.mapper: 'DEBUG'




