spring:
  profiles:
    active: develop
    include: 'database'
  
  jpa:
    generate_ddl: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      database: H2
      show_sql: true
      format_sql: true
  thymeleaf:
    cache: false

  pidfile: shared/tmp/pids/application.pid
server:
  port: 10001


logging:
    level:
        org.springframework: 'OFF'
        com.xiaojiuwo.models.mapper: 'DEBUG'


---
spring:
  profiles: develop

---
spring:
  profiles: test

---
spring:
  profiles: demo

---
spring:
  profiles: production