spring:
  profiles:
    active: develop
    include: database
  
  thymeleaf:
    cache: false

  pidfile: shared/tmp/pids/application.pid
server:
  port: 10001
security.oauth2.resource.filter-order: 3

logging:
    level:
        org.springframework: 'OFF'
        com.xiaojiuwo.models.mapper: 'DEBUG'


---
spring:
  profiles: develop

---
spring:
  profiles: test

---
spring:
  profiles: demo

---
spring:
  profiles: production